library(data.table)
library(JWileymisc)
library(extraoperators)
library(multilevelcoda)
library(multilevelTools)
library(emmeans)
library(doFuture)
library(compositions)
library(zCompositions)

library(bayestestR)
library(brms)
library(lme4)
library(loo)
library(performance)

library(ggplot2)
library(scales)
library(cowplot)
library(visreg)
library(ggthemes)
library(viridis)
library(tidyr)
library(gt)
library(gridExtra) 
library(ggpubr)
library(wesanderson)
library(hrbrthemes)
library(ggsci)
library(stats)
library(patchwork)
library(hrbrthemes)
library(latex2exp)

expand.grid.df <- function(...) Reduce(function(...) merge.data.frame(..., by = NULL, all = TRUE), list(...))

outputdir <- "/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/projects/multilevelecoda-sleep-stages/sleep-stages-affect/data/"
